"""add_uncertainty_columns

Revision ID: 1c5ace02cb5f
Revises: 
Create Date: 2025-11-24 16:39:44.444070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c5ace02cb5f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query_executions",
        sa.Column("forecast_uncertainty_gco2_kwh", sa.Float(), nullable=True),
    )
    op.add_column(
        "query_metrics", sa.Column("energy_std_dev_joules", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query_metrics", "energy_std_dev_joules")
    op.drop_column("query_executions", "forecast_uncertainty_gco2_kwh")
    # ### end Alembic commands ###
